server:
  port: 8081
spring:
  application:
    name: doctor-service
  cloud:
    compatibility-verifier:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://shinkansen.proxy.rlwy.net:48598/railway}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:yIWMnmMBiULXeDZIogRKIGXzpYxIHghT}
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  data:
    elasticsearch:
      uris: ${SPRING_DATA_ELASTICSEARCH_URIS:https://hospital-cluster-5303791460.us-east-1.bonsaisearch.net:443}
      username: ${SPRING_DATA_ELASTICSEARCH_USERNAME:j78qu5rxgf}
      password: ${SPRING_DATA_ELASTICSEARCH_PASSWORD:c3y0l8bm9z}
      ssl:
        enabled: true
        verification-mode: none

  flyway:
    enabled: false
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false

# Deshabilitar Eureka en producción
# Configuración de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFERIPADDRESS:true}
    hostname: ${HOSTNAME:localhost}

logging:
  level:
    com.hn.tgu.hospital: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: DEBUG
    co.elastic.clients: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    elasticsearch:
      enabled: false

springdoc:
  swagger-ui:
    path: /doctors/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs


# Configuración personalizada para Elasticsearch
elasticsearch:
  enabled: ${ELASTICSEARCH_ENABLED:true}
  fallback-enabled: ${ELASTICSEARCH_FALLBACK_ENABLED:false}
  retry-attempts: 3
  retry-delay: 5000