server:
  port: 8081

spring:
  profiles:
    active: prod  # o "prod" en despliegue
  application:
    name: doctor-service
  cloud:
    compatibility-verifier:
      enabled: false
  main:
    allow-bean-definition-overriding: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: Doctor Service
    description: Servicio para gestión de doctores
    version: 1.0.0

